#!/usr/bin/env python3
# Regenerate hardware/rtl/nco_lut_init.vh — 1024-entry sincos LUT init
# block included verbatim by nco_direct. Each entry packs:
#   [35:18] = cos(2π·i/1024) · 131071, signed 18-bit
#   [17: 0] = sin(2π·i/1024) · 131071, signed 18-bit
#
# Inlined because Vivado synthesis discards $sin/$cos in initial blocks
# with "Synth 8-311 non-constant assignment" — the LUT then has no
# driver and reads return 0 (NCO produces zero output, multiplying the
# whole DDC/DUC chain by zero).
#
# Usage: python3 tools/gen_nco_lut.py > hardware/rtl/nco_lut_init.vh

import math

print("// Auto-generated by tools/gen_nco_lut.py — do not edit.")
print("// 1024-entry sin/cos LUT for nco_direct. Each entry packs:")
print("//   [35:18] = cos(2pi*i/1024) * 131071, signed 18-bit")
print("//   [17: 0] = sin(2pi*i/1024) * 131071, signed 18-bit")
print("// Inlined as explicit assignments because Vivado synth ignores")
print("// $sin/$cos in initial blocks (Synth 8-311 warning).")
for i in range(1024):
    th = 2.0 * math.pi * i / 1024.0
    s = int(round(math.sin(th) * 131071.0))
    c = int(round(math.cos(th) * 131071.0))
    s18 = s & 0x3FFFF
    c18 = c & 0x3FFFF
    packed = (c18 << 18) | s18
    print(f"sincos_lut[{i:4d}] = 36'h{packed:09X};")
